#!/bin/sh
# -*- mode: sh -*-

SCRIPT_NAME="${0##*/}"
SCRIPT_RPATH="${0%$SCRIPT_NAME}"
SCRIPT_PATH=`cd "${SCRIPT_RPATH:-.}" && pwd`

FILES_FROM="${1:-{{ pi_sync_share_list }}}"
FROM="${2:-{{ pi_sync_share_from }}}"
TO="${3:-{{ pi_sync_share_to }}}"


if [ ! -r "$FILES_FROM" ]; then
    echo >&2 "could not read files list: \"$FILES_FROM\""
    exit 1
fi
if [ -z "$FROM" ]; then
    echo >&2 "source \"$FROM\" is empty"
    exit 1
fi
if [ -z "$TO" ]; then
    echo >&2 "target \"$TO\" is empty"
    exit 1
fi

rsync -av --delete --force -r --files-from="$FILES_FROM" "$FROM" "$TO"
